services:
  Dbp\Relay\EducationalcredentialsBundle\Controller\:
    resource: '../../Controller'
    autoconfigure: true
    autowire: true

  Dbp\Relay\EducationalcredentialsBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\EducationalcredentialsBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\EducationalcredentialsBundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

  Dbp\Relay\EducationalcredentialsBundle\Service\ConfigService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\EducationalcredentialsBundle\Service\DiplomaProviderInterface:
    '@Dbp\Relay\EducationalcredentialsBundle\Service\ExternalApi'
