services:
  Dbp\Relay\EducationalcredentialsBundle\ApiPlatform\:
    resource: '../../ApiPlatform'
    autoconfigure: true
    autowire: true

  Dbp\Relay\EducationalcredentialsBundle\Service\ExternalApi:
    autowire: true
    autoconfigure: true

  Dbp\Relay\EducationalcredentialsBundle\Service\ConfigService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\EducationalcredentialsBundle\Service\DiplomaProviderInterface:
    '@Dbp\Relay\EducationalcredentialsBundle\Service\ExternalApi'
